apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsr1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fsr1
  template:
    metadata:
      labels:
        app: fsr1
    spec:
      containers:
      - name: fsr1
        image: lazyyy77/fsr1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fsr1-service
spec:
  selector:
    app: fsr1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
