apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsr1-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bsr1
  template:
    metadata:
      labels:
        app: bsr1
    spec:
      containers:
      - name: bsr1
        image: lazyyy77/bsr1
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bsr1-service
spec:
  selector:
    app: bsr1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32000
  type: NodePort
