# dockerfile of bsr1
# 使用官方 OpenJDK 21 JRE 镜像作为基础镜像
FROM openjdk:21-jdk-slim

# 将编译好的 JAR 文件复制到容器中
COPY backend-1.0-SNAPSHOT.jar /backend-1.0-SNAPSHOT.jar

# 运行 JAR 文件
ENTRYPOINT ["java", "-jar", "/backend-1.0-SNAPSHOT.jar"]

# 暴露端口 8000
EXPOSE 8000
